config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }
  root to: 'top#index'
  resources :deal
  get '/mypage', to: 'users#mypage'
end

app/models/after_buy_chat.rb
class AfterBuyChat < ApplicationRecord
  belongs_to :users
  belongs_to :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/before_buy_chat.rb
class BeforeBuyChat < ApplicationRecord
  belongs_to :users
  belongs_to :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :after_buy_chats
  has_many :before_buy_chats
  has_many :item_likes
  belongs_to :users
  belongs_to :sessions
end

app/models/item_like.rb
class ItemLike < ApplicationRecord
  belongs_to :users
  belongs_to :items
end

app/models/professor.rb
class Professor < ApplicationRecord
  has_many :sessions
end

app/models/session.rb
class Session < ApplicationRecord
  has_many :session_reviews
  has_many :items
  belongs_to :professors
end

app/models/session_review.rb
class SessionReview < ApplicationRecord
  belongs_to :sessions
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :before_buy_chats
  has_many :after_buy_chats
  has_many :item_likes
  has_many :user_reviews

  validates :name, presence: true
  validates :uid, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :accepted, presence: { message: 'を入力してください' }
end

app/models/user_review.rb
class UserReview < ApplicationRecord
  belongs_to :users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action

  protected

    def configure_permitted_parameters
      added_attrs = [ :name, :uid, :email, :password, :password_confirmation, :accepted ]
      devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    end
end

app/controllers/deal_controller.rb
class DealController < ApplicationController
  def index
    #code
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def mypage
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deal_helper.rb
module DealHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PocketTerrace</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="default-container">
      <% if current_user %>
        <%= render 'layouts/shared/header' %>
      <% end %>
      <%= yield %>

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

    </div>

  </body>
</html>

app/views/layouts/shared/_header.html.erb
<header class="pc-header visible-pc">
  <div class="pc-header-inner">
    <div class="clearfix">
      <div class="l-left">
        <%= link_to image_tag('/assets/mercari.svg', :alt => 'PocketTerrace', width: "134", height: "36"), root_path %>
      </div>
      <%= form_for '#', html: { class: 'pc-header-form l-right' } do |f| %>
        <%= f.search_field :keyword,  placeholder: 'キーワードから探す', class: 'input-default' %>
        <i class="icon-search"></i>
      <% end %>
    </div>

    <div class="pc-header-nav-box clearfix">
      <nav class="nav-left">
        <ul class="pc-header-nav">
          <li>
            <h2><%= link_to "授業で探す", '#', class: 'pc-header-nav-root' %></h2>
          </li>
          <li>
            <h2><%= link_to "教授で探す", '#', class: 'pc-header-nav-root' %></h2>
          </li>
        </ul>
      </nav>
      <div class="nav-right">
        <ul class="pc-header-user-nav">
          <li>
            <%= link_to(mypage_path, class: 'sp-header-user-icon pc-header-nav-root') do %>
              <figure>
              </figure>
              <h2>マイページ</h2>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</header>